spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrap-servers:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Configurações específicas da aplicação
app:
  kafka:
    topic:
      sales: ${kafka.topic.sales:sales}
    bootstrap-servers: ${kafka.bootstrap-servers:localhost:9092}
    group-id: ${kafka.group-id:flink-sales-aggregation}

logging:
  level:
    org.springframework.kafka: INFO
    com.crisaltmann.flinkcountsales: INFO